/** Fixtures shaped exactly like real API responses. */

import type {
  AnalysisRunDetail,
  DashboardSummary,
  GovernanceReport,
  HealthResponse,
  Project,
  ProjectDocument,
} from '@/types/api'

export const health: HealthResponse = {
  status: 'healthy',
  application: 'AI Business Process Discovery Agent',
  version: '0.1.0',
  environment: 'development',
  llm_provider: 'ollama',
  llm_model: 'llama3.2',
  embedding_provider: 'ollama',
  embeddings_are_semantic: true,
  minimum_evidence_score: 0.35,
}

export const project: Project = {
  id: 'project-1',
  name: 'Accounts Payable Review',
  client_name: 'Northwind Ltd',
  department: 'Finance',
  industry: 'Manufacturing',
  objective: 'Understand and improve the invoice approval process.',
  status: 'active',
  created_at: '2026-08-01T09:00:00Z',
  updated_at: '2026-08-02T09:00:00Z',
}

export const indexedDocument: ProjectDocument = {
  id: 'document-1',
  project_id: 'project-1',
  original_filename: 'invoice-process.pdf',
  content_type: 'application/pdf',
  file_extension: '.pdf',
  size_bytes: 245_760,
  created_at: '2026-08-01T10:00:00Z',
  index_status: 'indexed',
  index_error: null,
  indexed_at: '2026-08-01T10:00:12Z',
  page_count: 4,
  word_count: 1_820,
  character_count: 11_400,
  chunk_count: 12,
  detected_document_type: 'pdf',
}

export const failedDocument: ProjectDocument = {
  ...indexedDocument,
  id: 'document-2',
  original_filename: 'scan.pdf',
  index_status: 'failed',
  index_error: 'Text could not be extracted. The file may be scanned.',
  indexed_at: null,
  chunk_count: 0,
  word_count: null,
}

export const completedRun: AnalysisRunDetail = {
  id: 'run-1',
  project_id: 'project-1',
  question: 'How does the invoice approval process work end to end?',
  status: 'completed',
  current_stage: 'completed',
  governance_status: 'allowed',
  governance_stage: 'final_invariant',
  terminal_state_name: null,
  human_review_required: false,
  source_count: 2,
  created_at: '2026-08-02T10:00:00Z',
  started_at: '2026-08-02T10:00:01Z',
  completed_at: '2026-08-02T10:02:30Z',
  top_k: 5,
  minimum_similarity_score: null,
  document_id_filters: [],
  errors: [],
  denial_summary: null,
  process_analysis: {
    summary: 'Invoices arrive by email and are keyed in manually.',
    findings: [
      {
        title: 'Manual invoice entry',
        description: 'A clerk keys each invoice into the finance system.',
        category: 'process',
        severity: 'medium',
        evidence_source_ids: ['Source 1'],
        recommendation: 'Confirm the volume with the AP team lead.',
      },
    ],
    assumptions: [],
    insufficient_evidence: ['Invoice volumes per month'],
    confidence: 0.72,
    provider_name: 'ollama',
    model_name: 'llama3.2',
  },
  bottleneck_analysis: {
    summary: 'Approvals wait in manager inboxes.',
    findings: [
      {
        title: 'Approval sits three to five days',
        description: 'There is no reminder on manager approvals.',
        category: 'bottleneck',
        severity: 'high',
        evidence_source_ids: ['Source 1'],
        recommendation: 'Add an automated reminder after 24 hours.',
      },
    ],
    assumptions: [],
    insufficient_evidence: [],
    confidence: 0.68,
    provider_name: 'ollama',
    model_name: 'llama3.2',
  },
  risk_analysis: {
    summary: 'Manual keying creates a control weakness.',
    findings: [
      {
        title: 'Transcription errors are uncontrolled',
        description: 'No second check catches keying mistakes before approval.',
        category: 'risk',
        severity: 'critical',
        evidence_source_ids: ['Source 2'],
        recommendation: 'Introduce a three-way match before approval.',
      },
      {
        title: 'Approval evidence is in email',
        description: 'Approvals live in personal inboxes rather than the system.',
        category: 'control',
        severity: 'low',
        evidence_source_ids: ['Source 1'],
        recommendation: 'Record approvals in the finance system.',
      },
    ],
    assumptions: [],
    insufficient_evidence: [],
    confidence: 0.7,
    provider_name: 'ollama',
    model_name: 'llama3.2',
  },
  automation_analysis: {
    summary: 'Invoice capture is a strong automation candidate.',
    findings: [
      {
        title: 'Automate invoice capture',
        description: 'Line items follow a consistent structure.',
        category: 'opportunity',
        severity: 'high',
        evidence_source_ids: ['Source 1'],
        recommendation: 'Pilot OCR capture with human review of exceptions.',
      },
    ],
    assumptions: [],
    insufficient_evidence: [],
    confidence: 0.66,
    provider_name: 'ollama',
    model_name: 'llama3.2',
  },
  final_analysis: {
    summary:
      'Invoice approval is manual end to end, with the largest delay at manager approval.',
    findings: [
      {
        title: 'Start with approval reminders',
        description: 'The cheapest change with the largest effect on cycle time.',
        category: 'opportunity',
        severity: 'high',
        evidence_source_ids: ['Source 1'],
        recommendation: 'Add reminders, then pilot capture automation.',
      },
    ],
    assumptions: [
      { description: 'Volumes are stable', reason: 'No volume data was supplied.' },
    ],
    insufficient_evidence: ['Cost per invoice'],
    confidence: 0.71,
    provider_name: 'ollama',
    model_name: 'llama3.2',
  },
  citations: [
    {
      source_id: 'Source 1',
      document_id: 'document-1',
      chunk_id: 'chunk-a',
      chunk_index: 0,
      score: 0.83,
      filename: 'invoice-process.pdf',
    },
    {
      source_id: 'Source 2',
      document_id: 'document-1',
      chunk_id: 'chunk-b',
      chunk_index: 1,
      score: 0.71,
      filename: 'invoice-process.pdf',
    },
  ],
  retrieval_provider: 'ollama',
  retrieval_model: 'nomic-embed-text',
  retrieved_count: 2,
  context_truncated: false,
}

export const blockedRun: AnalysisRunDetail = {
  ...completedRun,
  id: 'run-2',
  status: 'governance_blocked',
  current_stage: 'governance_blocked',
  governance_status: 'blocked',
  terminal_state_name: 'UNSUPPORTED_FINDINGS',
  denial_summary: {
    construct_name: 'risk_scope_invariant',
    denial_type: 'InvariantViolation',
    safe_reason: 'Governance denied automated execution at risk_scope_invariant.',
    terminal_state_name: 'UNSUPPORTED_FINDINGS',
    human_review_required: false,
  },
  automation_analysis: null,
  final_analysis: null,
}

export const governanceReport: GovernanceReport = {
  analysis_run_id: 'run-1',
  project_id: 'project-1',
  question: completedRun.question,
  workflow_status: 'completed',
  governance_status: 'allowed',
  governance_stage: 'final_invariant',
  terminal_state_name: null,
  human_review_required: false,
  denial_summary: null,
  errors: [],
  decisions: [
    {
      sequence: 0,
      decision_id: 'decision-1',
      node_name: 'discover_process',
      construct_name: 'process_discovery_pre_node',
      construct_type: 'pre_node',
      outcome: 'allowed',
      source_count: 2,
      confidence: null,
      terminal_state_name: null,
      recorded_at: '2026-08-02T10:00:05Z',
    },
    {
      sequence: 1,
      decision_id: 'decision-2',
      node_name: 'validate_evidence_reference_invariant',
      construct_name: 'evidence_reference_invariant',
      construct_type: 'invariant',
      outcome: 'allowed',
      source_count: 2,
      confidence: null,
      terminal_state_name: null,
      recorded_at: '2026-08-02T10:00:40Z',
    },
  ],
  ledger_entries: [
    {
      entry_id: 'entry-1',
      sequence: 0,
      entry_type: 'MONITOR',
      identity_key: 'process-discovery:workflow-1',
      instance_id: 'workflow-1',
      decision_id: 'decision-1',
      caused_by: null,
      payload: { node_name: 'discover_process', outcome: 'allowed', source_count: 2 },
      timestamp: 1_754_128_805,
      prev_hash: '0'.repeat(64),
      entry_hash: 'a'.repeat(64),
    },
  ],
  chain_verified: true,
  checkpoint_sequence: 20,
  checkpoint_hash: 'b'.repeat(64),
  audit_checks: [
    {
      name: 'pre_node_has_verification',
      label: 'Gate decisions were verified',
      passed: true,
      explanation: 'Every governance gate that ran has a matching verification record.',
      violation_count: 0,
    },
    {
      name: 'terminal_has_human_authorised_transition',
      label: 'Stopped runs were human-authorised',
      passed: false,
      explanation:
        'This application has no human approval or re-enablement workflow, so a stopped run has no recorded human sign-off.',
      violation_count: 1,
    },
  ],
  certificate_issued: false,
  certificate_hash: null,
  certificate_note:
    'This certificate does not guarantee no Inadmissible State was ever reached.',
}

export const dashboard: DashboardSummary = {
  project_count: 2,
  document_count: 5,
  indexed_document_count: 4,
  documents_pending_count: 0,
  documents_failed_count: 1,
  analysis_total_count: 3,
  analysis_completed_count: 2,
  analysis_running_count: 0,
  analysis_failed_count: 0,
  analysis_blocked_count: 1,
  analysis_human_review_count: 0,
  risk_finding_count: 4,
  risk_severity: { critical: 1, high: 1, medium: 2, low: 0, informational: 0 },
  automation_opportunity_count: 3,
  bottleneck_finding_count: 2,
  recent_activity: [
    {
      kind: 'analysis',
      title: 'How does the invoice approval process work?',
      subtitle: 'Analysis completed',
      project_id: 'project-1',
      project_name: 'Accounts Payable Review',
      analysis_run_id: 'run-1',
      status: 'completed',
      occurred_at: '2026-08-02T10:00:00Z',
    },
    {
      kind: 'document',
      title: 'invoice-process.pdf',
      subtitle: 'Document indexed',
      project_id: 'project-1',
      project_name: 'Accounts Payable Review',
      analysis_run_id: null,
      status: 'indexed',
      occurred_at: '2026-08-01T10:00:00Z',
    },
  ],
}
